# Generated by Django 4.2.1 on 2023-06-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_time_listing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='creation_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
