# Generated by Django 4.2.1 on 2023-06-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('new', 'Brand New'), ('opened', 'Opened'), ('used', 'Used'), ('not_working', 'Not working')], max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.ForeignKey(default=1, on_delete=models.SET('No condition'), related_name='status', to='auctions.condition'),
            preserve_default=False,
        ),
    ]
