# Generated by Django 4.2.1 on 2023-06-30 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_condition_listing_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='condition',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='auctions.condition'),
        ),
    ]
