# Generated by Django 4.2.1 on 2023-07-01 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_condition_condition_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='creation_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
