# Generated by Django 4.2.1 on 2023-07-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_user_listings_listing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
