# Generated by Django 4.2.1 on 2023-07-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_listing_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[(None, 'No category'), ('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home_garden', 'Home & Garden'), ('beauty_health', 'Beauty & Health'), ('books', 'Books'), ('movies_music', 'Movies & Music'), ('collectibles', 'Collectibles'), ('automotive', 'Automotive'), ('toys_games', 'Toys & Games'), ('jewelry', 'Jewelry'), ('sporting_goods', 'Sporting Goods'), ('hobbies', 'Hobbies'), ('art_crafts', 'Art and Crafts'), ('home_appliances', 'Home Appliances'), ('baby_kids', 'Baby and Kids'), ('musical_instruments', 'Musical Instruments'), ('pet_supplies', 'Pet Supplies')], default=None, max_length=64),
        ),
    ]
