# Generated by Django 4.2.1 on 2023-07-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_bid_user_id_alter_bid_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='bid',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
