# Generated by Django 4.2.1 on 2023-07-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_rename_bid_bid_price_rename_user_id_bid_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
