# Generated by Django 4.2.1 on 2023-07-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_listing_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='active_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], default='active', max_length=16),
        ),
    ]
