# Generated by Django 4.2.1 on 2023-07-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_alter_listing_active_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='closed',
        ),
    ]
