# Generated by Django 4.2.1 on 2023-07-08 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home_and_garden', 'Home & Garden'), ('collectibles', 'Collectibles'), ('music_movies', 'Music & Movies'), ('books', 'Books'), ('sporting_goods', 'Sporting Goods'), ('automotive', 'Automotive'), ('toys_hobbies', 'Toys & Hobbies'), ('health_beauty', 'Health & Beauty'), ('home_appliances', 'Home Appliances'), ('jewelry_watches', 'Jewelry & Watches'), ('art_crafts', 'Art & Crafts'), ('baby_kids', 'Baby & Kids'), ('musical_instruments', 'Musical Instruments'), ('pet_supplies', 'Pet Supplies'), (None, 'Other')], default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('new', 'Brand New'), ('opened', 'Opened'), ('used', 'Used'), ('not_working', 'Not working')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(max_length=256),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_bid',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.time'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='winner',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
    ]
