# Generated by Django 4.2.5 on 2023-10-16 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_alter_listing_category_alter_listing_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('fashion_and_clothes', 'Fashion & Clothes'), ('home_and_garden', 'Home & Garden'), ('collectibles', 'Collectibles'), ('music_movies', 'Music & Movies'), ('books', 'Books'), ('sporting_goods', 'Sporting Goods'), ('automotive', 'Automotive'), ('toys_hobbies', 'Toys & Hobbies'), ('health_beauty', 'Health & Beauty'), ('home_appliances', 'Home Appliances'), ('jewelry_watches', 'Jewelry & Watches'), ('art_crafts', 'Art & Crafts'), ('baby_kids', 'Baby & Kids'), ('musical_instruments', 'Musical Instruments'), ('pet_supplies', 'Pet Supplies'), (None, 'Other')], default=None, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='UserBiddingActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_listing', to='auctions.listing')),
                ('active_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_bidding_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
