# Generated by Django 4.2.5 on 2023-10-20 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_alter_listing_category_userbiddingactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='time',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
